import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}bg-[#fcf5f5]`}>
        <div className="sticky top-0 bg-[#ffffff]">

          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
